---
name: sqlite3
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/crystal-lang/crystal-sqlite3.git" "sqlite3"
  - run: shards install
    working-directory: sqlite3
  - run: crystal spec
    working-directory: sqlite3
