---
name: noir
inputs:
  shell:
    type: string
    default: bash
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/owasp-noir/noir.git" "noir"
    shell: ${{ inputs.shell }}
  - run: shards install --skip-postinstall --skip-executables
    working-directory: noir
    shell: ${{ inputs.shell }}
  - run: shards build $CRYSTAL_FLAGS
    working-directory: noir
    shell: ${{ inputs.shell }}
  - run: crystal spec $CRYSTAL_FLAGS
    working-directory: noir
    shell: ${{ inputs.shell }}
