---
name: webmock
inputs:
  shell:
    type: string
    default: bash
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/manastech/webmock.cr.git" "webmock"
    shell: ${{ inputs.shell }}
  - run: shards install
    working-directory: webmock
    shell: ${{ inputs.shell }}
  - run: crystal spec
    working-directory: webmock
    shell: ${{ inputs.shell }}
