---
name: lexbor
inputs:
  shell:
    type: string
    default: bash
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/kostya/lexbor.git" "lexbor"
    shell: ${{ inputs.shell }}
  - run: shards install
    working-directory: lexbor
    shell: ${{ inputs.shell }}
  - run: crystal spec
    working-directory: lexbor
    shell: ${{ inputs.shell }}
