---
name: teeplate
inputs:
  shell:
    type: string
    default: bash
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/luckyframework/teeplate.git" "teeplate"
    shell: ${{ inputs.shell }}
  - run: shards install
    working-directory: teeplate
    shell: ${{ inputs.shell }}
  - run: crystal spec
    working-directory: teeplate
    shell: ${{ inputs.shell }}
