---
name: kemal
inputs:
  shell:
    type: string
    default: bash
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/kemalcr/kemal.git" "kemal"
    shell: ${{ inputs.shell }}
  - run: shards install
    working-directory: kemal
    shell: ${{ inputs.shell }}
  - run: crystal spec
    working-directory: kemal
    shell: ${{ inputs.shell }}
