---
name: stumpy_gif
inputs:
  shell:
    type: string
    default: bash
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/stumpycr/stumpy_gif.git" "stumpy_gif"
    shell: ${{ inputs.shell }}
  - run: shards install --skip-postinstall --skip-executables
    working-directory: stumpy_gif
    shell: ${{ inputs.shell }}
  - run: crystal spec $CRYSTAL_FLAGS
    working-directory: stumpy_gif
    shell: ${{ inputs.shell }}
