---
name: lucky_router
inputs:
  shell:
    type: string
    default: bash
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/luckyframework/lucky_router.git" "lucky_router"
    shell: ${{ inputs.shell }}
  - run: shards install --skip-postinstall --skip-executables
    working-directory: lucky_router
    shell: ${{ inputs.shell }}
  - run: crystal spec
    working-directory: lucky_router
    shell: ${{ inputs.shell }}
