---
name: mysql
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/crystal-lang/crystal-mysql.git" "mysql"
  - run: shards install
    working-directory: mysql
  - run: crystal spec
    working-directory: mysql
