---
name: db
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/crystal-lang/crystal-db.git" "db"
  - run: shards install
    working-directory: db
  - run: crystal spec
    working-directory: db
