---
name: slang
inputs:
  shell:
    type: string
    default: bash
runs:
  using: composite
  steps:
  - run: git clone "https://github.com/jeromegn/slang.cr" "slang"
    shell: ${{ inputs.shell }}
  - run: shards install
    working-directory: slang
    shell: ${{ inputs.shell }}
  - run: crystal spec
    working-directory: slang
    shell: ${{ inputs.shell }}
