---
name: crystal
"on":
  push: 
  pull_request: 
  workflow_dispatch:
    inputs:
      crystal:
        type: string
        default: nightly
      shards:
        type: string
        default: nightly
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: sudo apt-get install --quiet --yes --no-install-recommends fossil mercurial
    - if: success() || failure()
      name: 'Project: crystal'
      uses: ./.github/actions/crystal
    - if: success() || failure()
      name: 'Project: shards'
      uses: ./.github/actions/shards
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: brew install fossil mercurial
    - if: success() || failure()
      name: 'Project: crystal'
      uses: ./.github/actions/crystal
    - if: success() || failure()
      name: 'Project: shards'
      uses: ./.github/actions/shards
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: choco install --no-progress fossil hg
    - run: git config --global core.autocrlf false
    - uses: ilammy/msvc-dev-cmd@v1
    - if: success() || failure()
      name: 'Project: crystal'
      uses: ./.github/actions/crystal
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: shards'
      uses: ./.github/actions/shards
      with:
        shell: pwsh
