---
name: db
"on":
  push: 
  pull_request: 
  workflow_dispatch:
    inputs:
      crystal:
        type: string
        default: nightly
      shards:
        type: string
        default: nightly
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "5.7"
    - uses: ikalnytskyi/action-setup-postgres@v8
      with:
        postgres-version: "16"
    - name: Install system dependencies
      run: sudo apt-get install --quiet --yes --no-install-recommends libsqlite3-dev
    - if: success() || failure()
      name: 'Project: mysql'
      uses: ./.github/actions/mysql
    - if: success() || failure()
      name: 'Project: pg'
      uses: ./.github/actions/pg
    - if: success() || failure()
      name: 'Project: avram'
      uses: ./.github/actions/avram
    - if: success() || failure()
      name: 'Project: db'
      uses: ./.github/actions/db
    - if: success() || failure()
      name: 'Project: sqlite3'
      uses: ./.github/actions/sqlite3
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "5.7"
    - uses: ikalnytskyi/action-setup-postgres@v8
      with:
        postgres-version: "16"
    - name: Install system dependencies
      run: brew install sqlite
    - if: success() || failure()
      name: 'Project: mysql'
      uses: ./.github/actions/mysql
    - if: success() || failure()
      name: 'Project: pg'
      uses: ./.github/actions/pg
    - if: success() || failure()
      name: 'Project: avram'
      uses: ./.github/actions/avram
    - if: success() || failure()
      name: 'Project: db'
      uses: ./.github/actions/db
    - if: success() || failure()
      name: 'Project: sqlite3'
      uses: ./.github/actions/sqlite3
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "5.7"
    - uses: ikalnytskyi/action-setup-postgres@v8
      with:
        postgres-version: "16"
    - run: git config --global core.autocrlf false
    - uses: ilammy/msvc-dev-cmd@v1
    - if: success() || failure()
      name: 'Project: mysql'
      uses: ./.github/actions/mysql
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: pg'
      uses: ./.github/actions/pg
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: avram'
      uses: ./.github/actions/avram
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: db'
      uses: ./.github/actions/db
      with:
        shell: pwsh
