---
name: Formats
"on":
  push: 
  pull_request: 
  workflow_dispatch:
    inputs:
      crystal:
        type: string
        default: nightly
jobs:
  Formats:
    runs-on: ubuntu-latest
    steps:
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: minitest
      run: crystal tool format
    - name: mysql
      run: crystal tool format
    - name: sync
      run: crystal tool format
    - name: lavinmq
      run: make format
    - name: db
      run: crystal tool format
    - name: sqlite3
      run: crystal tool format
