---
name: Projects
"on":
  push: 
  pull_request: 
  workflow_dispatch:
    inputs:
      crystal:
        type: string
        default: nightly
      shards:
        type: string
        default: nightly
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: lucky'
      uses: ./.github/actions/lucky
    - if: success() || failure()
      name: 'Project: teeplate'
      uses: ./.github/actions/teeplate
    - if: success() || failure()
      name: 'Project: luck_router'
      uses: ./.github/actions/luck_router
    - if: success() || failure()
      name: 'Project: shell-table'
      uses: ./.github/actions/shell-table
    - if: success() || failure()
      name: 'Project: wordsmith'
      uses: ./.github/actions/wordsmith
    - if: success() || failure()
      name: 'Project: lucky_task'
      uses: ./.github/actions/lucky_task
    - if: success() || failure()
      name: 'Project: habitat'
      uses: ./.github/actions/habitat
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: lucky'
      uses: ./.github/actions/lucky
    - if: success() || failure()
      name: 'Project: teeplate'
      uses: ./.github/actions/teeplate
    - if: success() || failure()
      name: 'Project: luck_router'
      uses: ./.github/actions/luck_router
    - if: success() || failure()
      name: 'Project: shell-table'
      uses: ./.github/actions/shell-table
    - if: success() || failure()
      name: 'Project: wordsmith'
      uses: ./.github/actions/wordsmith
    - if: success() || failure()
      name: 'Project: lucky_task'
      uses: ./.github/actions/lucky_task
    - if: success() || failure()
      name: 'Project: habitat'
      uses: ./.github/actions/habitat
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - run: git config --global core.autocrlf false
    - if: success() || failure()
      name: 'Project: lucky'
      uses: ./.github/actions/lucky
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: teeplate'
      uses: ./.github/actions/teeplate
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: luck_router'
      uses: ./.github/actions/luck_router
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: shell-table'
      uses: ./.github/actions/shell-table
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: wordsmith'
      uses: ./.github/actions/wordsmith
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: lucky_task'
      uses: ./.github/actions/lucky_task
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: habitat'
      uses: ./.github/actions/habitat
      with:
        shell: pwsh
