---
name: Projects
"on":
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      crystal:
        type: string
        default: nightly
      shards:
        type: string
        default: nightly
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  shards-windows:
    runs-on: windows-latest
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: ilammy/msvc-dev-cmd@v1
    - if: success() || failure()
      name: 'Project: timecop'
      uses: ./.github/actions/timecop
