---
name: Projects
"on":
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      crystal:
        type: string
        default: nightly
      shards:
        type: string
        default: nightly
      flags:
        type: string
        default: ""
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
env:
  CRYSTAL_FLAGS: ${{ inputs.flags }}
jobs:
  athena-framework-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: sudo apt-get install --quiet --yes --no-install-recommends libmagic-dev
    - if: success() || failure()
      name: 'Project: athena'
      uses: ./.github/actions/athena
  athena-framework-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: brew install libmagic
    - if: success() || failure()
      name: 'Project: athena'
      uses: ./.github/actions/athena
  shards-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: pustovitDmytro/redis-github-action@v1.0.1
    - name: Install system dependencies
      run: sudo apt-get install --quiet --yes --no-install-recommends libsass-dev
    - if: success() || failure()
      name: 'Project: minitest'
      uses: ./.github/actions/minitest
    - if: success() || failure()
      name: 'Project: stumpy_jpeg'
      uses: ./.github/actions/stumpy_jpeg
    - if: success() || failure()
      name: 'Project: webmock'
      uses: ./.github/actions/webmock
    - if: success() || failure()
      name: 'Project: slang'
      uses: ./.github/actions/slang
    - if: success() || failure()
      name: 'Project: radix'
      uses: ./.github/actions/radix
    - if: success() || failure()
      name: 'Project: http_proxy'
      uses: ./.github/actions/http_proxy
    - if: success() || failure()
      name: 'Project: totem'
      uses: ./.github/actions/totem
    - if: success() || failure()
      name: 'Project: sass'
      uses: ./.github/actions/sass
    - if: success() || failure()
      name: 'Project: kemal-session'
      uses: ./.github/actions/kemal-session
    - if: success() || failure()
      name: 'Project: bindata'
      uses: ./.github/actions/bindata
    - if: success() || failure()
      name: 'Project: msgpack'
      uses: ./.github/actions/msgpack
    - if: success() || failure()
      name: 'Project: sync'
      uses: ./.github/actions/sync
    - if: success() || failure()
      name: 'Project: markd'
      uses: ./.github/actions/markd
    - if: success() || failure()
      name: 'Project: crinja'
      uses: ./.github/actions/crinja
    - if: success() || failure()
      name: 'Project: future'
      uses: ./.github/actions/future
    - if: success() || failure()
      name: 'Project: halite'
      uses: ./.github/actions/halite
    - if: success() || failure()
      name: 'Project: timecop'
      uses: ./.github/actions/timecop
    - if: success() || failure()
      name: 'Project: exception_page'
      uses: ./.github/actions/exception_page
    - if: success() || failure()
      name: 'Project: stumpy_gif'
      uses: ./.github/actions/stumpy_gif
    - if: success() || failure()
      name: 'Project: stumpy_core'
      uses: ./.github/actions/stumpy_core
    - if: success() || failure()
      name: 'Project: backtracer'
      uses: ./.github/actions/backtracer
    - if: success() || failure()
      name: 'Project: pretty'
      uses: ./.github/actions/pretty
    - if: success() || failure()
      name: 'Project: kemal'
      uses: ./.github/actions/kemal
    - if: success() || failure()
      name: 'Project: lexbor'
      uses: ./.github/actions/lexbor
    - if: success() || failure()
      name: 'Project: baked_file_system'
      uses: ./.github/actions/baked_file_system
    - if: success() || failure()
      name: 'Project: openssl_ext'
      uses: ./.github/actions/openssl_ext
    - if: success() || failure()
      name: 'Project: admiral'
      uses: ./.github/actions/admiral
    - if: success() || failure()
      name: 'Project: random'
      uses: ./.github/actions/random
  shards-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: pustovitDmytro/redis-github-action@v1.0.1
    - name: Install system dependencies
      run: brew install libsass
    - if: success() || failure()
      name: 'Project: minitest'
      uses: ./.github/actions/minitest
    - if: success() || failure()
      name: 'Project: stumpy_jpeg'
      uses: ./.github/actions/stumpy_jpeg
    - if: success() || failure()
      name: 'Project: webmock'
      uses: ./.github/actions/webmock
    - if: success() || failure()
      name: 'Project: slang'
      uses: ./.github/actions/slang
    - if: success() || failure()
      name: 'Project: radix'
      uses: ./.github/actions/radix
    - if: success() || failure()
      name: 'Project: http_proxy'
      uses: ./.github/actions/http_proxy
    - if: success() || failure()
      name: 'Project: totem'
      uses: ./.github/actions/totem
    - if: success() || failure()
      name: 'Project: sass'
      uses: ./.github/actions/sass
    - if: success() || failure()
      name: 'Project: kemal-session'
      uses: ./.github/actions/kemal-session
    - if: success() || failure()
      name: 'Project: bindata'
      uses: ./.github/actions/bindata
    - if: success() || failure()
      name: 'Project: msgpack'
      uses: ./.github/actions/msgpack
    - if: success() || failure()
      name: 'Project: sync'
      uses: ./.github/actions/sync
    - if: success() || failure()
      name: 'Project: markd'
      uses: ./.github/actions/markd
    - if: success() || failure()
      name: 'Project: crinja'
      uses: ./.github/actions/crinja
    - if: success() || failure()
      name: 'Project: future'
      uses: ./.github/actions/future
    - if: success() || failure()
      name: 'Project: halite'
      uses: ./.github/actions/halite
    - if: success() || failure()
      name: 'Project: timecop'
      uses: ./.github/actions/timecop
    - if: success() || failure()
      name: 'Project: exception_page'
      uses: ./.github/actions/exception_page
    - if: success() || failure()
      name: 'Project: stumpy_gif'
      uses: ./.github/actions/stumpy_gif
    - if: success() || failure()
      name: 'Project: stumpy_core'
      uses: ./.github/actions/stumpy_core
    - if: success() || failure()
      name: 'Project: backtracer'
      uses: ./.github/actions/backtracer
    - if: success() || failure()
      name: 'Project: kemal'
      uses: ./.github/actions/kemal
    - if: success() || failure()
      name: 'Project: lexbor'
      uses: ./.github/actions/lexbor
    - if: success() || failure()
      name: 'Project: baked_file_system'
      uses: ./.github/actions/baked_file_system
    - if: success() || failure()
      name: 'Project: openssl_ext'
      uses: ./.github/actions/openssl_ext
    - if: success() || failure()
      name: 'Project: admiral'
      uses: ./.github/actions/admiral
    - if: success() || failure()
      name: 'Project: random'
      uses: ./.github/actions/random
  shards-windows:
    runs-on: windows-latest
    steps:
    - run: git config --global core.autocrlf false
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: pustovitDmytro/redis-github-action@v1.0.1
    - if: success() || failure()
      name: 'Project: minitest'
      uses: ./.github/actions/minitest
    - if: success() || failure()
      name: 'Project: stumpy_jpeg'
      uses: ./.github/actions/stumpy_jpeg
    - if: success() || failure()
      name: 'Project: webmock'
      uses: ./.github/actions/webmock
    - if: success() || failure()
      name: 'Project: slang'
      uses: ./.github/actions/slang
    - if: success() || failure()
      name: 'Project: radix'
      uses: ./.github/actions/radix
    - if: success() || failure()
      name: 'Project: http_proxy'
      uses: ./.github/actions/http_proxy
    - if: success() || failure()
      name: 'Project: totem'
      uses: ./.github/actions/totem
    - if: success() || failure()
      name: 'Project: kemal-session'
      uses: ./.github/actions/kemal-session
    - if: success() || failure()
      name: 'Project: bindata'
      uses: ./.github/actions/bindata
    - if: success() || failure()
      name: 'Project: msgpack'
      uses: ./.github/actions/msgpack
    - if: success() || failure()
      name: 'Project: sync'
      uses: ./.github/actions/sync
    - if: success() || failure()
      name: 'Project: markd'
      uses: ./.github/actions/markd
    - if: success() || failure()
      name: 'Project: crinja'
      uses: ./.github/actions/crinja
    - if: success() || failure()
      name: 'Project: future'
      uses: ./.github/actions/future
    - if: success() || failure()
      name: 'Project: halite'
      uses: ./.github/actions/halite
    - if: success() || failure()
      name: 'Project: timecop'
      uses: ./.github/actions/timecop
    - if: success() || failure()
      name: 'Project: exception_page'
      uses: ./.github/actions/exception_page
    - if: success() || failure()
      name: 'Project: stumpy_gif'
      uses: ./.github/actions/stumpy_gif
    - if: success() || failure()
      name: 'Project: stumpy_core'
      uses: ./.github/actions/stumpy_core
    - if: success() || failure()
      name: 'Project: kemal'
      uses: ./.github/actions/kemal
    - if: success() || failure()
      name: 'Project: openssl_ext'
      uses: ./.github/actions/openssl_ext
    - if: success() || failure()
      name: 'Project: admiral'
      uses: ./.github/actions/admiral
    - if: success() || failure()
      name: 'Project: random'
      uses: ./.github/actions/random
  crystal-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: sudo apt-get install --quiet --yes --no-install-recommends fossil mercurial
    - if: success() || failure()
      name: 'Project: crystal'
      uses: ./.github/actions/crystal
    - if: success() || failure()
      name: 'Project: perf-tools'
      uses: ./.github/actions/perf-tools
    - if: success() || failure()
      name: 'Project: shards'
      uses: ./.github/actions/shards
  crystal-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: brew install fossil mercurial
    - if: success() || failure()
      name: 'Project: crystal'
      uses: ./.github/actions/crystal
    - if: success() || failure()
      name: 'Project: perf-tools'
      uses: ./.github/actions/perf-tools
    - if: success() || failure()
      name: 'Project: shards'
      uses: ./.github/actions/shards
  crystal-windows:
    runs-on: windows-latest
    steps:
    - run: git config --global core.autocrlf false
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: choco install --no-progress fossil hg
    - if: success() || failure()
      name: 'Project: crystal'
      uses: ./.github/actions/crystal
  db-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "5.7"
    - uses: ikalnytskyi/action-setup-postgres@v8
      with:
        postgres-version: "16"
    - name: Install system dependencies
      run: sudo apt-get install --quiet --yes --no-install-recommends libsqlite3-dev
        libsqlite3-dev
    - if: success() || failure()
      name: 'Project: mysql'
      uses: ./.github/actions/mysql
    - if: success() || failure()
      name: 'Project: pg'
      uses: ./.github/actions/pg
    - if: success() || failure()
      name: 'Project: granite'
      uses: ./.github/actions/granite
    - if: success() || failure()
      name: 'Project: avram'
      uses: ./.github/actions/avram
    - if: success() || failure()
      name: 'Project: db'
      uses: ./.github/actions/db
    - if: success() || failure()
      name: 'Project: sqlite3'
      uses: ./.github/actions/sqlite3
  db-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "5.7"
    - uses: ikalnytskyi/action-setup-postgres@v8
      with:
        postgres-version: "16"
    - name: Install system dependencies
      run: brew install sqlite sqlite
    - if: success() || failure()
      name: 'Project: mysql'
      uses: ./.github/actions/mysql
    - if: success() || failure()
      name: 'Project: pg'
      uses: ./.github/actions/pg
    - if: success() || failure()
      name: 'Project: granite'
      uses: ./.github/actions/granite
    - if: success() || failure()
      name: 'Project: avram'
      uses: ./.github/actions/avram
    - if: success() || failure()
      name: 'Project: db'
      uses: ./.github/actions/db
    - if: success() || failure()
      name: 'Project: sqlite3'
      uses: ./.github/actions/sqlite3
  db-windows:
    runs-on: windows-latest
    steps:
    - run: git config --global core.autocrlf false
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "5.7"
    - uses: ikalnytskyi/action-setup-postgres@v8
      with:
        postgres-version: "16"
    - if: success() || failure()
      name: 'Project: mysql'
      uses: ./.github/actions/mysql
    - if: success() || failure()
      name: 'Project: pg'
      uses: ./.github/actions/pg
    - if: success() || failure()
      name: 'Project: avram'
      uses: ./.github/actions/avram
    - if: success() || failure()
      name: 'Project: db'
      uses: ./.github/actions/db
  luckyframework-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: lucky'
      uses: ./.github/actions/lucky
    - if: success() || failure()
      name: 'Project: lucky_router'
      uses: ./.github/actions/lucky_router
    - if: success() || failure()
      name: 'Project: wordsmith'
      uses: ./.github/actions/wordsmith
    - if: success() || failure()
      name: 'Project: lucky_task'
      uses: ./.github/actions/lucky_task
    - if: success() || failure()
      name: 'Project: habitat'
      uses: ./.github/actions/habitat
  luckyframework-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: lucky'
      uses: ./.github/actions/lucky
    - if: success() || failure()
      name: 'Project: lucky_router'
      uses: ./.github/actions/lucky_router
    - if: success() || failure()
      name: 'Project: wordsmith'
      uses: ./.github/actions/wordsmith
    - if: success() || failure()
      name: 'Project: lucky_task'
      uses: ./.github/actions/lucky_task
    - if: success() || failure()
      name: 'Project: habitat'
      uses: ./.github/actions/habitat
  luckyframework-windows:
    runs-on: windows-latest
    steps:
    - run: git config --global core.autocrlf false
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: lucky'
      uses: ./.github/actions/lucky
    - if: success() || failure()
      name: 'Project: lucky_router'
      uses: ./.github/actions/lucky_router
    - if: success() || failure()
      name: 'Project: wordsmith'
      uses: ./.github/actions/wordsmith
    - if: success() || failure()
      name: 'Project: lucky_task'
      uses: ./.github/actions/lucky_task
    - if: success() || failure()
      name: 'Project: habitat'
      uses: ./.github/actions/habitat
  tools-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: ameba'
      uses: ./.github/actions/ameba
    - if: success() || failure()
      name: 'Project: liger'
      uses: ./.github/actions/liger
  tools-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: ameba'
      uses: ./.github/actions/ameba
    - if: success() || failure()
      name: 'Project: liger'
      uses: ./.github/actions/liger
  tools-windows:
    runs-on: windows-latest
    steps:
    - run: git config --global core.autocrlf false
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: liger'
      uses: ./.github/actions/liger
  apps-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: sudo apt-get install --quiet --yes --no-install-recommends libsqlite3-dev
        libxml2-utils etcd-server liblz4-dev libxml2-dev libsqlite3-dev
    - if: success() || failure()
      name: 'Project: noir'
      uses: ./.github/actions/noir
    - if: success() || failure()
      name: 'Project: invidious'
      uses: ./.github/actions/invidious
    - if: success() || failure()
      name: 'Project: mint-lang'
      uses: ./.github/actions/mint-lang
    - if: success() || failure()
      name: 'Project: coverage-reporter'
      uses: ./.github/actions/coverage-reporter
    - if: success() || failure()
      name: 'Project: lavinmq'
      uses: ./.github/actions/lavinmq
    - if: success() || failure()
      name: 'Project: ktistec'
      uses: ./.github/actions/ktistec
  apps-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - name: Install system dependencies
      run: brew install libxml2
    - if: success() || failure()
      name: 'Project: mint-lang'
      uses: ./.github/actions/mint-lang
