---
name: stumpy
"on":
  push: 
  pull_request: 
  workflow_dispatch:
    inputs:
      crystal:
        type: string
        default: nightly
      shards:
        type: string
        default: nightly
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: stumpy_jpeg'
      uses: ./.github/actions/stumpy_jpeg
    - if: success() || failure()
      name: 'Project: stumpy_bmp'
      uses: ./.github/actions/stumpy_bmp
    - if: success() || failure()
      name: 'Project: stumpy_png'
      uses: ./.github/actions/stumpy_png
    - if: success() || failure()
      name: 'Project: stumpy_gif'
      uses: ./.github/actions/stumpy_gif
    - if: success() || failure()
      name: 'Project: stumpy_core'
      uses: ./.github/actions/stumpy_core
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - if: success() || failure()
      name: 'Project: stumpy_jpeg'
      uses: ./.github/actions/stumpy_jpeg
    - if: success() || failure()
      name: 'Project: stumpy_bmp'
      uses: ./.github/actions/stumpy_bmp
    - if: success() || failure()
      name: 'Project: stumpy_png'
      uses: ./.github/actions/stumpy_png
    - if: success() || failure()
      name: 'Project: stumpy_gif'
      uses: ./.github/actions/stumpy_gif
    - if: success() || failure()
      name: 'Project: stumpy_core'
      uses: ./.github/actions/stumpy_core
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ github.event.inputs.crystal || 'nightly' }}
        shards: ${{ github.event.inputs.shards || 'nightly' }}
    - run: git config --global core.autocrlf false
    - if: success() || failure()
      name: 'Project: stumpy_jpeg'
      uses: ./.github/actions/stumpy_jpeg
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: stumpy_bmp'
      uses: ./.github/actions/stumpy_bmp
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: stumpy_png'
      uses: ./.github/actions/stumpy_png
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: stumpy_gif'
      uses: ./.github/actions/stumpy_gif
      with:
        shell: pwsh
    - if: success() || failure()
      name: 'Project: stumpy_core'
      uses: ./.github/actions/stumpy_core
      with:
        shell: pwsh
